version: '3'

services:
    nodejs-app:
        build:
          context: ./node
        container_name: nodejsserver
        hostname: nodejsserver
        networks:
            - example-net
    nginx:
        image: nginx:latest
        volumes:
            - /Docker2/nginx/nginx.conf:/etc/nginx/nginx.conf
        container_name: nginxserver
        hostname: nginx
        ports:
            - "80:80"
        depends_on:
            - nodejs-app
        networks:
            - example-net

networks:
  example-net:
